### ISSUE TITLE
the app should allow users to toggle between 'basic' and 'power caller' mode

### ISSUE THREAD

**Issue by obra** [CAVaccineInventory/help.vaccinate#16]
Some callers have told us that they really don't feel comfortable asking some of the detailed questions about inventory numbers, customer excitement, problems, etc.

We should have a mode in the app where folks who are not up for the heavy data gathering don't have to wade through it to do their jobs.

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
