### ISSUE TITLE
Mechanism for ensuring VIAL doesn't break when we add new availability tags

### ISSUE THREAD

**Issue by simonw** [CAVaccineInventory/help.vaccinate#166]
VIAL validates incoming availability tags against this known list of tags: https://vial-staging.calltheshots.us/api/availabilityTags

Every now and then a new tag gets added over here without VIAL knowing about it, which causes errors. Most recent example: https://github.com/CAVaccineInventory/vial/issues/178 (fixed in https://github.com/CAVaccineInventory/vial/issues/168)

I can think of three ways we could stop that from happening:

1. Establish a process where new tags aren't added to the client app without first being added to VIAL
2. Have the client app hit the https://vial-staging.calltheshots.us/api/availabilityTags endpoint to find out what availability tags are available before showing them to users
3. VIAL could learn to occasionally accept an unknown availability tag, add it to the database in a "draft" state and wait for someone to come and fill in the details later.

My preference is for options 1 or 2. What do you think would work best here?

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
