### ISSUE TITLE
use bootstrap tooltips to better display hover tooltips

### ISSUE THREAD

**Issue by al63** [CAVaccineInventory/help.vaccinate#216]
Right now we have a bunch of labels via "title" on our buttons that display tooltips. It would be nice if these tooltips displayed with bootstrap tooltips. We already do this for the "report an error" link.

Ideally we can do this in a way that makes it easy for QA to continue adding tooltips themselves.

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
