### ISSUE TITLE
Prevent callers submitting malformed website URLs

### ISSUE THREAD

**Issue by al63** [CAVaccineInventory/help.vaccinate#235]
Sometimes callers and phone bankers will set the website url without a `https://` prefix. We should try to make that hard - require that `http://` or `https://` is at the beginning of the website string and prefill `https://` if no known URLs exist (making sure to not allow http:// on it's own to be submitted)

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
