### ISSUE TITLE
Add back date validation for planned_closure. Don't allow closures in the past.

### ISSUE THREAD

**Issue by al63** [CAVaccineInventory/help.vaccinate#249]
I removed this code because I didn't realize setting a date with a `yyyy-mm-dd` string assumes UTC, at least on chrome, so comparing dates is wrong-ish.

I also don't trust Date.parse in general because of Browser Nonsense, so we probably could rely on regex to capture group out the year/day/month and then compare that.

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
