### ISSUE TITLE
We need to think about handling call recording failures

### ISSUE THREAD

**Issue by obra** [CAVaccineInventory/help.vaccinate#25]
I 5% wonder if when we get there it would be overkill to be writing them to a message bus or event queue.
That sounds like "fun, but more trouble than it's worth" unless we otherwise need to write backoff and error handling code

I am thinking about mitigations for problems we don't have today
And I do not want to mess up our stack now.
But figured that I should write down my words, rather than dropping the thought entirely on the floor

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
