### ISSUE TITLE
User-friendly login flow

### ISSUE THREAD

**Issue by obra** [CAVaccineInventory/help.vaccinate#26]
I'd love to eventually get auth working like the demo on https://netlify-auth0-rbac.netlify.app/ / https://marketplace.auth0.com/integrations/netlify-role-management where if they hit the site without creds they just get told to log in without loading the 'real' app

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
