### ISSUE TITLE
Guide / enforce correct phone number format in Scooby

### ISSUE THREAD

**Issue by kimberlyd17** [CAVaccineInventory/help.vaccinate#299]
If possible, could we standardize phone number formatting in Scooby? 

Ideally these would be acceptable:
1-800-123-1234
(123) 123-1234
(123) 123-1234 Ext 123

But these would not:
123.123.1234
123.1234
1234567890
as well as not anything more erratic (123.1231231 etc)

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
