### ISSUE TITLE
Change from "Veterans only" to "Veterans, Spouses, Caregivers, and CHAMPVA"

### ISSUE THREAD

**Issue by kimberlyd17** [CAVaccineInventory/help.vaccinate#309]
Update this button and website text to reflect the default status at the VA. Per discussion [here](https://discord.com/channels/799147121357881364/832339092985348186/842184789636546581).
If any different restrictions come up, a caller/web-banker would add in Public Notes, but this seems to be the default.

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
