### ISSUE TITLE
Prompt in Script to ask about ages offered for Pfizer

### ISSUE THREAD

**Issue by kimberlyd17** [CAVaccineInventory/help.vaccinate#310]
When "Pfizer" is selected in the vaccine type multi-select, pop up a yellow bar with a note "Pfizer is now authorized for ages 12+ Please ask which ages this location is currently vaccinating and include this in the Public notes." 

This will remind callers to get the latest information about ages that this location has progressed to vaccinating.

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
