### ISSUE TITLE
"Other" Vaccine button

### ISSUE THREAD

**Issue by EveCoff** [CAVaccineInventory/help.vaccinate#329]
The "other" button for type of vaccine currently serves no purpose and seems to be confusing some volunteer callers. ( a few have put "other" when the location was unable to tell them what vaccine was being used.) Could this button be removed from the  Scooby script and then if/when there's another approved vaccine, it can be put back in?  @kimberlyd17 @lisabettefay

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
