### ISSUE TITLE
fix walk-in pop-up warning

### ISSUE THREAD

**Issue by lisabettefay** [CAVaccineInventory/help.vaccinate#332]
can we adjust the language of this warning:

![image](https://user-images.githubusercontent.com/81186147/119913373-ca17fa00-bf2b-11eb-87cc-73ef24306416.png)

text should say: `Locations that accept walk-ins should be accompanied by days and times for walk-ins, if relevant. Fill in the public or private notes fields as necessary with details.`

This warning only seems to be triggering on reports tagged as `appts and walk-ins` submitted w/o any private notes. 

@EveCoff @kimberlyd17

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
