### ISSUE TITLE
add indication of location_type to scooby

### ISSUE THREAD

**Issue by lisabettefay** [CAVaccineInventory/help.vaccinate#333]
having the `location_type` display for callers (who have no other indication of the type of location they are calling) would be useful.

Perhaps we could replace the (County) info that is no longer updated/doesnt exist that you see in the location header in scooby?

![image](https://user-images.githubusercontent.com/81186147/120899181-63b26c00-c5fc-11eb-8ad8-a06e97549567.png)

CC: @EveCoff @kimberlyd17 @obra

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
